Created a rudimentary save system to save the base game files. Method…
connorlunsford/text-based-adventure-game pull request #28
Opened 2021-05-10 03:11 UTC by connorlunsford

… is system.save_base_game_files

2021-05-13 09:40 UTC, oborna approved these changes
Great work!

2021-05-13 09:59 UTC, oborna requested changes, later dismissed
Upon looking at the merge conflict, it looks like add_connection() and remove_connection() in the Room class need to be fixed so that they use the changes that were added to them last week (e.g., raising exceptions instead of returning True/False).

2021-05-15 17:28 UTC, connorlunsford reviewed
Finished making those changes in the room class. Should be fixed now, go ahead and approve it.

2021-05-15 17:32 UTC, jenniferbriere approved these changes

2021-05-15 17:33 UTC, jenniferbriere approved these changes

2021-05-15 17:35 UTC, merged